src/Entity/Monster.php
<?php

namespace App\Entity;

use App\Repository\MonsterRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MonsterRepository::class)]
class Monster
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $monsterName = null;

    #[ORM\Column]
    private ?int $stat_atk = null;

    #[ORM\Column]
    private ?int $stat_def = null;

    #[ORM\Column]
    private ?int $stat_hp = null;

    #[ORM\Column]
    private ?int $stat_atkspd = null;

    #[ORM\Column]
    private ?float $stat_critrate = null;

    #[ORM\Column]
    private ?float $stat_critdmg = null;

    #[ORM\Column]
    private ?float $stat_accuracy = null;

    #[ORM\Column]
    private ?float $stat_res = null;

    #[ORM\Column]
    private ?float $stat_prec = null;

    #[ORM\Column]
    private ?float $stat_evasion = null;

    #[ORM\ManyToOne(inversedBy: 'monstersName')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Attribute $attribute = null;

    #[ORM\ManyToOne(inversedBy: 'monsterName')]
    #[ORM\JoinColumn(nullable: false)]
    private ?ClassMonster $class = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMonsterName(): ?string
    {
        return $this->monsterName;
    }

    public function setMonsterName(string $monsterName): static
    {
        $this->monsterName = $monsterName;

        return $this;
    }

    public function getStatAtk(): ?int
    {
        return $this->stat_atk;
    }

    public function setStatAtk(int $stat_atk): static
    {
        $this->stat_atk = $stat_atk;

        return $this;
    }

    public function getStatDef(): ?int
    {
        return $this->stat_def;
    }

    public function setStatDef(int $stat_def): static
    {
        $this->stat_def = $stat_def;

        return $this;
    }

    public function getStatHp(): ?int
    {
        return $this->stat_hp;
    }

    public function setStatHp(int $stat_hp): static
    {
        $this->stat_hp = $stat_hp;

        return $this;
    }

    public function getStatAtkspd(): ?int
    {
        return $this->stat_atkspd;
    }

    public function setStatAtkspd(int $stat_atkspd): static
    {
        $this->stat_atkspd = $stat_atkspd;

        return $this;
    }

    public function getStatCritrate(): ?float
    {
        return $this->stat_critrate;
    }

    public function setStatCritrate(float $stat_critrate): static
    {
        $this->stat_critrate = $stat_critrate;

        return $this;
    }

    public function getStatCritdmg(): ?float
    {
        return $this->stat_critdmg;
    }

    public function setStatCritdmg(float $stat_critdmg): static
    {
        $this->stat_critdmg = $stat_critdmg;

        return $this;
    }

    public function getStatAccuracy(): ?float
    {
        return $this->stat_accuracy;
    }

    public function setStatAccuracy(float $stat_accuracy): static
    {
        $this->stat_accuracy = $stat_accuracy;

        return $this;
    }

    public function getStatRes(): ?float
    {
        return $this->stat_res;
    }

    public function setStatRes(float $stat_res): static
    {
        $this->stat_res = $stat_res;

        return $this;
    }

    public function getStatPrec(): ?float
    {
        return $this->stat_prec;
    }

    public function setStatPrec(float $stat_prec): static
    {
        $this->stat_prec = $stat_prec;

        return $this;
    }

    public function getStatEvasion(): ?float
    {
        return $this->stat_evasion;
    }

    public function setStatEvasion(float $stat_evasion): static
    {
        $this->stat_evasion = $stat_evasion;

        return $this;
    }

    public function getAttribute(): ?Attribute
    {
        return $this->attribute;
    }

    public function setAttribute(?Attribute $attribute): static
    {
        $this->attribute = $attribute;

        return $this;
    }

    public function getClass(): ?ClassMonster
    {
        return $this->class;
    }

    public function setClass(?ClassMonster $class): static
    {
        $this->class = $class;

        return $this;
    }
}

src/Form/MonsterType.php
<?php

namespace App\Form;

use App\Entity\Monster;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MonsterType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('monsterName')
            ->add('stat_atk')
            ->add('stat_def')
            ->add('stat_hp')
            ->add('stat_atkspd')
            ->add('stat_critrate')
            ->add('stat_critdmg')
            ->add('stat_accuracy')
            ->add('stat_res')
            ->add('stat_prec')
            ->add('stat_evasion')
            ->add('attribute')
            ->add('class')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Monster::class,
        ]);
    }
}

src/Controller/MonsterController.php
<?php

namespace App\Controller;

use App\Entity\Monster;
use App\Form\MonsterType;
use App\Repository\MonsterRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/monster')]
class MonsterController extends AbstractController
{
    #[Route('/', name: 'app_monster_index', methods: ['GET'])]
    public function index(MonsterRepository $monsterRepository): Response
    {
        return $this->render('monster/index.html.twig', [
            'monsters' => $monsterRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_monster_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $monster = new Monster();
        $form = $this->createForm(MonsterType::class, $monster);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($monster);
            $entityManager->flush();

            return $this->redirectToRoute('app_monster_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('monster/new.html.twig', [
            'monster' => $monster,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_monster_show', methods: ['GET'])]
    public function show(Monster $monster): Response
    {
        return $this->render('monster/show.html.twig', [
            'monster' => $monster,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_monster_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Monster $monster, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MonsterType::class, $monster);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_monster_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('monster/edit.html.twig', [
            'monster' => $monster,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_monster_delete', methods: ['POST'])]
    public function delete(Request $request, Monster $monster, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$monster->getId(), $request->request->get('_token'))) {
            $entityManager->remove($monster);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_monster_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/monster/_delete_form.html.twig
<form method="post" action="{{ path('app_monster_delete', {'id': monster.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ monster.id) }}">
    <button class="btn">Delete</button>
</form>

templates/monster/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/monster/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Monster{% endblock %}

{% block body %}
    <h1>Edit Monster</h1>

    {{ include('monster/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_monster_index') }}">back to list</a>

    {{ include('monster/_delete_form.html.twig') }}
{% endblock %}

templates/monster/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Monster index{% endblock %}

{% block body %}
    <h1>Monster index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>MonsterName</th>
                <th>Stat_atk</th>
                <th>Stat_def</th>
                <th>Stat_hp</th>
                <th>Stat_atkspd</th>
                <th>Stat_critrate</th>
                <th>Stat_critdmg</th>
                <th>Stat_accuracy</th>
                <th>Stat_res</th>
                <th>Stat_prec</th>
                <th>Stat_evasion</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for monster in monsters %}
            <tr>
                <td>{{ monster.id }}</td>
                <td>{{ monster.monsterName }}</td>
                <td>{{ monster.statAtk }}</td>
                <td>{{ monster.statDef }}</td>
                <td>{{ monster.statHp }}</td>
                <td>{{ monster.statAtkspd }}</td>
                <td>{{ monster.statCritrate }}</td>
                <td>{{ monster.statCritdmg }}</td>
                <td>{{ monster.statAccuracy }}</td>
                <td>{{ monster.statRes }}</td>
                <td>{{ monster.statPrec }}</td>
                <td>{{ monster.statEvasion }}</td>
                <td>
                    <a href="{{ path('app_monster_show', {'id': monster.id}) }}">show</a>
                    <a href="{{ path('app_monster_edit', {'id': monster.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="13">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_monster_new') }}">Create new</a>
{% endblock %}

templates/monster/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Monster{% endblock %}

{% block body %}
    <h1>Create new Monster</h1>

    {{ include('monster/_form.html.twig') }}

    <a href="{{ path('app_monster_index') }}">back to list</a>
{% endblock %}

templates/monster/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Monster{% endblock %}

{% block body %}
    <h1>Monster</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ monster.id }}</td>
            </tr>
            <tr>
                <th>MonsterName</th>
                <td>{{ monster.monsterName }}</td>
            </tr>
            <tr>
                <th>Stat_atk</th>
                <td>{{ monster.statAtk }}</td>
            </tr>
            <tr>
                <th>Stat_def</th>
                <td>{{ monster.statDef }}</td>
            </tr>
            <tr>
                <th>Stat_hp</th>
                <td>{{ monster.statHp }}</td>
            </tr>
            <tr>
                <th>Stat_atkspd</th>
                <td>{{ monster.statAtkspd }}</td>
            </tr>
            <tr>
                <th>Stat_critrate</th>
                <td>{{ monster.statCritrate }}</td>
            </tr>
            <tr>
                <th>Stat_critdmg</th>
                <td>{{ monster.statCritdmg }}</td>
            </tr>
            <tr>
                <th>Stat_accuracy</th>
                <td>{{ monster.statAccuracy }}</td>
            </tr>
            <tr>
                <th>Stat_res</th>
                <td>{{ monster.statRes }}</td>
            </tr>
            <tr>
                <th>Stat_prec</th>
                <td>{{ monster.statPrec }}</td>
            </tr>
            <tr>
                <th>Stat_evasion</th>
                <td>{{ monster.statEvasion }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_monster_index') }}">back to list</a>

    <a href="{{ path('app_monster_edit', {'id': monster.id}) }}">edit</a>

    {{ include('monster/_delete_form.html.twig') }}
{% endblock %}